### ISSUE TITLE
Formatting to eep18 from proplist does not work correctly with lists (example.field)

### ISSUE THREAD

**Issue by danieljharris** [nalundgaard/jsn#29]
```erlang
1> Test = jsn:set(<<"comment.test">>, [], <<"testing_comment">>).
[{<<"comment">>,[{<<"test">>,<<"testing_comment">>}]}]

2> Output = jsn:new(Test, [{format, eep18}]).
{[{<<"comment">>,[{<<"test">>,<<"testing_comment">>}]}]}

3> Output == {[{<<"comment">>,{[{<<"test">>,<<"testing_comment">>}]}}]}.
false
```

**Comment by nalundgaard** [comment]
Daniel, 

Thanks for your report. This is actually how [`jsn:new/2`](https://github.com/nalundgaard/jsn#new012---create-a-new-object) works. 

> Given a `{Path, Value}` tuple or a list of such tuples, return a new object (in the default format) containing the given path(s) and value(s).

You passed in a nested proplist to a function that expects a flat lists of paths and values. All it does is set the value at the path to what you gave it. So, If you give `[{<<"test">>,<<"testing_comment">>}]` as a value for the path `<<"comment">>`, that's exactly what you'll get, regardless of format.

There are a couple of ways that you can accomplish what you want to do:

1. Use a flat `{Path, Value}` list as `jsn:new/2` expects:
  ```erlang
  jsn:new([{<<"comment.test">>, <<"testing_comment">>}], [{format, eep18}]).
  {[{<<"comment">>,{[{<<"test">>,<<"testing_comment">>}]}}]}
  ```
2. Use the conversion functions in the library, in this case, [`jsn:from_proplist/2`](https://github.com/nalundgaard/jsn#as_map1-from_map12-as_proplist1-and-from_proplist12---object-format-conversion)
  ```erlang
  > Test = jsn:set(<<"comment.test">>, [], <<"testing_comment">>).
  [{<<"comment">>,[{<<"test">>,<<"testing_comment">>}]}]
  
  > Output = jsn:from_proplist(Test, [{format, eep18}]).
  {[{<<"comment">>,{[{<<"test">>,<<"testing_comment">>}]}}]}

  > Output == {[{<<"comment">>,{[{<<"test">>,<<"testing_comment">>}]}}]}.
  true
  ```

I'll go ahead and close this, but feel free to let me know if you have any other questions or concerns!

**Comment by danieljharris** [comment]
@nalundgaard Thank you for taking a look, I'll implement the from_proplist fix now :)

**Comment by danieljharris** [comment]
Just added it, works perfectly!
