### ISSUE TITLE
delete adds entries when using deep paths

### ISSUE THREAD

**Issue by heyoka** [nalundgaard/jsn#33]
Hi, first of all thank you for this useful library.

There is a problen when using non existing deep-paths in the `delete `or `delete_list `functions, jsn adds entries:

```
jsn:delete({<<"baz">>,<<"boz">>}, #{<<"foo">> => 1, <<"bar">> => 2}).
#{<<"bar">> => 2,<<"baz">> => #{},<<"foo">> => 1}
```

```
jsn:delete(<<"baz.boz">>, #{<<"foo">> => 1, <<"bar">> => 2}). 
#{<<"bar">> => 2,<<"baz">> => #{},<<"foo">> => 1}
```

expected output should be:
`#{<<"foo">> => 1, <<"bar">> => 2}`

**Comment by nalundgaard** [comment]
Thanks so much for this report and the clear example. 🤦‍♂ on my part! I have opened #34 to fix that and add test coverage of this case.

**Comment by heyoka** [comment]
Perfect, thank you !
