### ISSUE TITLE
New feature idea: with/2

### ISSUE THREAD

**Issue by nalundgaard** [nalundgaard/jsn#35]
Idea:

```erlang
jsn:with(Paths, Object)
```

Essentially `maps:with/1`, but with support for nested paths.

```erlang
> jsn:with([<<"foo.bar">>, <<"foo.baz">>],
           #{<<"foo">> => #{<<"bar">> => 1,
                            <<"baz">> => 1,
                            <<"fum">> => 1}}).
#{<<"foo">> => #{<<"bar">> => 1, <<"baz">> => 1}}.
```

Generally I'd want to support the full path spec (array indices/refs in particular) and all existing object formats, making this a little project. What do you think @mrallen1?

**Comment by jadeallenx** [comment]
I support this idea. Anything that makes it easier/obvious to select elements is a win.

**Comment by jadeallenx** [comment]
It wouldn't take too much extra work to implement `without/1` too, tbh...

**Comment by nalundgaard** [comment]
I assume you mean `without/2`. I think that it's technically implemented already via `delete_list/2`, but it would be interesting to implement that using a less memory-intensive algorithm.

**Comment by jadeallenx** [comment]
Yeah that's what I meant :)
